version: '3'
services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    restart: always
    ports:
      - 8123:8123
    volumes:
      - homeassistant_config:/config

volumes:
  homeassistant_config:

